### ISSUE TITLE
Author notes not shown in non-PDF formats

### ISSUE THREAD

**Issue by cbrnr** [wjschne/apaquarto#113]
Author notes are not included in non-PDF formats (i.e., docx, typst, html) if no `author-note` section is present in the header.

Here's a minimal example that demonstrates the missing author notes for `apaquarto-docx` (but the same happens for `apaquarto-html`; `apaquarto-typst` does not work, see #114):

```
---
title: "My Paper's Title: A Full Analysis of Everything"
shorttitle: "My Paper's Title"
author:
  - name: W. Joel Schneider
    corresponding: true
    orcid: 0000-0002-8393-5316
    email: schneider@temple.edu
    affiliations:
      - name: Temple University
        department: College of Education and Human Development
        address: 1301 Cecil B. Moore Ave.
        city: Philadelphia
        region: PA
        postal-code: 19122-6091
abstract: "This is my abstract."
keywords: [keyword1, keyword2]
format:
  apaquarto-docx: default
---
```

<img width="634" alt="Image" src="https://github.com/user-attachments/assets/282a5285-65e4-44dc-a29c-f6729a3850e5" />

Note that the same header works if you only change the `format` to `apaquarto-pdf`.

Interestingly, author notes are shown in all format if I include the `author-note` field, e.g.

```
author-note:
  disclosures:
    conflict of interest: The author has no conflict of interest to declare.
```

<img width="623" alt="Image" src="https://github.com/user-attachments/assets/8ab25737-9691-4225-9823-9c9e32c3730b" />

However, the actual `conflict of interest` statement is not included in the output document, which is also a bit unexpected.

Also (sorry for the multiple issues, let me know if I should open a new one), the ORCID URLs are not hyperlinks in the Word document.

I'm using Quarto 1.6.42 and apaquarto 4.3.10 on macOS.
