### ISSUE TITLE
Error when rendering to apaquarto-typst

### ISSUE THREAD

**Issue by cbrnr** [wjschne/apaquarto#114]
I get an error when rendering to `apaquarto-typst`, for example with the following document:

```
---
title: "My Paper's Title: A Full Analysis of Everything"
shorttitle: "My Paper's Title"
author:
  - name: W. Joel Schneider
    corresponding: true
    orcid: 0000-0002-8393-5316
    email: schneider@temple.edu
    affiliations:
      - name: Temple University
        department: College of Education and Human Development
        address: 1301 Cecil B. Moore Ave.
        city: Philadelphia
        region: PA
        postal-code: 19122-6091
abstract: "This is my abstract."
keywords: [keyword1, keyword2]
format:
  apaquarto-typst: default
---
```

This will result in the following error:

```
[typst]: Compiling mwe.typ to mwe.pdf...error: file not found (searched at /Users/clemens/Projects/adds/article/\_extensions/wjschne/apaquarto/apa.csl)
    ┌─ article/mwe.typ:432:25
    │
432 │ #set bibliography(style: "\_extensions/wjschne/apaquarto/apa.csl") 
    │                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

I'm using Quarto 1.6.42 and apaquarto 4.3.10 on macOS.
