### ISSUE TITLE
Figure size control in `apatwocolumn` layout

### ISSUE THREAD

**Issue by franfrutos** [wjschne/apaquarto#126]
I'm trying to control the size of a figure when using the apatwocolumn layout, but I haven't been successful so far. I've tried different options (e.g., setting fig-width, fig-height, using out.width), but none seem to have an effect when using the two-column format. Is there a recommended way to resize figures in this layout?

Thanks again for your work on apaquarto.

**Comment by wjschne** [comment]
Can you show me a minimal example? For example, altering `fig-width` in this example, seems to work for me:

```yaml
---
title: "My Ttile"
author:
  - name: Ana Fulano
    corresponding: true
    orcid: 0000-0000-0000-0001
    email: sm@example.org
    affiliations:
        - name: Generic University
abstract: Minimal abstract
format:
  apaquarto-pdf:
    documentmode: jou
---
```

This is my paper (see @fig-twocolumn).

```r
#| label: fig-twocolumn
#| fig-cap: A Figure Spanning Two Columns
#| apa-twocolumn: true
#| fig-height: 3
#| fig-width: 5
#| fig-align: center
library(ggplot2)
ggplot(data.frame(x = c(-4, 4)), aes(x)) +
  stat_function(fun = dnorm, 
                geom = "area",
                n = 1000,
                color = NA,
                fill = "#41448780") +
  theme_void()
```

---


---
e_void()
```
