### ISSUE TITLE
Numbered lines error

### ISSUE THREAD

**Issue by DominiqueMakowski** [wjschne/apaquarto#34]
The rendering fails when I add numbered lines with the followig: 

```
Rendering PDF
running xelatex - 1
  This is XeTeX, Version 3.141592653-2.6-0.999995 (TeX Live 2023) (preloaded format=xelatex)
   restricted \write18 enabled.
  entering extended mode
  
updating tlmgr

updating existing packages
ERROR: 
compilation failed- error
Package edtable Error: ltabptch.sty (for improving spacing around
(edtable)                longtable) missing! Be sure to use it always
(edtable)                or never!.

See the edtable package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.260  }
         

see manuscript.log for more information
```

(it also seems like it keeps updating tlmgr every time)

Also, I get that we can easily get numbered line in word (#25), but for reproducibility and convenience it would be really cool to have them automatically if that's possible :)

**Comment by wjschne** [comment]
Is it fixed?

**Comment by DominiqueMakowski** [comment]
This is what I get in jou mode:

```
Rendering PDF
running xelatex - 1
  This is XeTeX, Version 3.141592653-2.6-0.999995 (TeX Live 2023) (preloaded format=xelatex)
   restricted \write18 enabled.
  entering extended mode
  
updating tlmgr

updating existing packages
ERROR: 
compilation failed- error
Package edtable Error: ltabptch.sty (for improving spacing around
(edtable)                longtable) missing! Be sure to use it always
(edtable)                or never!.

See the edtable package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.260  }
         

see manuscript.log for more information.
```

and in man mode the same:

```
Rendering PDF
running xelatex - 1
  This is XeTeX, Version 3.141592653-2.6-0.999995 (TeX Live 2023) (preloaded format=xelatex)
   restricted \write18 enabled.
  entering extended mode
  
updating tlmgr

updating existing packages
ERROR: 
compilation failed- error
Package edtable Error: ltabptch.sty (for improving spacing around
(edtable)                longtable) missing! Be sure to use it always
(edtable)                or never!.

See the edtable package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.260  }
         

see manuscript.log for more information
```

**Comment by DominiqueMakowski** [comment]
PS: this is my whole qmd file:

<details>
  <summary>full</summary>

```
---
title: "The Revised Interoceptive Accuracy Scale (IAS-R) Confirms Links between Interoception and Mental Health"
blank-lines-above-title: 2  # Lines above title in .docx format
shorttitle: "Revised Interoceptive Accuracy Scale (IAS-R)"
author:
  - name: Dominique Makowski
    corresponding: true
    orcid: "0000-0001-5375-9967"
    email: D.Makowski@sussex.ac.uk
    url: https://realitybending.github.io/
    # Roles are optional (note: The two writing roles have en dashes, not hyphens. You can use their aliases, w)
    # Select from the CRediT: Contributor Roles Taxonomy https://credit.niso.org/
    # Conceptualization, Data curation, Formal Analysis, Funding acquisition, Investigation, 
    # Methodology, Project administration, Resources, Software, Supervision, Validation, 
    # Visualization, Writing – original draft, Writing – review & editing
    roles:
      - conceptualization: lead
      - Writing - original draft
    affiliations:
      - id: id1
        name: "University of Sussex"
        group: Reality Bending Lab
        department: School of Psychology
        city: Brighton
        region: UK
        postal-code: "BN1 9RH"
  - name: X. Y
    # roles:
    #   - Project administration
    #   - Formal Analysis
    affiliations: 
      - ref: id1
  - name: Annabel Chen
    orcid: "0000-0002-1540-5516"
    # roles:
    #   - Resources
    #   - Project administration
    affiliations:
      - name: "School of Social Sciences, Nanyang Technological University, Singapore"
author-note:
  blank-lines-above-author-note: 1
abstract: "This document is a template demonstrating the apaquarto format."
keywords: [Interoception, Accuracy, Scale, Questionnaire, Personality, Psychopathology, Validation]
floatsintext: true
bibliography: "bibliography.bib"
format:
  apaquarto-docx:
    numbered-lines: false
  apaquarto-pdf:
    documentmode: man 
    numbered-lines: true
---

\`\`\`{r}
#| label: setup
#| include: false
library(conflicted)
library(tidyverse)
\`\`\`


Blqblq some reference [@cohen2003applied].

# Methods

blabla


# Results

blabla

# Discussion

blabla

# References


::: {#refs}
:::
```

</details>
