### ISSUE TITLE
Adding information to top-left of first page of "JOU"

### ISSUE THREAD

**Issue by drfurtado** [wjschne/apaquarto#38]
I was wondering if you could guide me on how to add some information (see attached image) on the top-left of the first page I render it as JOU?

Any help would be greatly appreciated. 

![Capture-2024-03-07-141450](https://github.com/wjschne/apaquarto/assets/9524571/47e00f5b-0dfa-451b-9f7c-314274720dd4)

**Comment by wjschne** [comment]
In the `volume` field, just add a `\\newline` to separate the lines. You can also put LaTeX formatting in the fields to achieve the effect you are looking for. For example:

``` yaml
format:
  apaquarto-pdf:
    journal: "\\bfseries \\scriptsize Journal of Kinesiology and Wellness"
    volume: "\\vskip 1mm A Publication of the Western Society for Kinesiology and Wellness\\newline Volume 12, Number 1, Pages 1--9, 2023\\newline ISSN# 2323-4505"
    documentmode: jou
```

**Comment by drfurtado** [comment]
> In the `volume` field, just add a `\\newline` to separate the lines. You can also put LaTeX formatting in the fields to achieve the effect you are looking for. For example:
> 
> ```yaml
> format:
>   apaquarto-pdf:
>     journal: "\\bfseries \\scriptsize Journal of Kinesiology and Wellness"
>     volume: "\\vskip 1mm A Publication of the Western Society for Kinesiology and Wellness\\newline Volume 12, Number 1, Pages 1--9, 2023\\newline ISSN# 2323-4505"
>     documentmode: jou
> ```

Excellent!
Is there a way to control the font size? The results is bit small compared to rest of the info on that page.
![image](https://github.com/wjschne/apaquarto/assets/9524571/a34708a3-c7bf-4ee8-a39a-7418ea9f7a65)

**Comment by wjschne** [comment]
Use `\vskip 2cm` to move the title down by 2cm. For example,
``` yaml
title: "\\vskip 2cm \\bfseries Acute Beetroot Supplementation May Improve Blood Pressure \\\\ But Not Exercise Economy in Female Masters Swimmers"
```
The [LaTeX commands for font size](https://en.wikibooks.org/wiki/LaTeX/Fonts): `\tiny \scriptsize \footnotesize \small \normalsize \large \Large \LARGE \huge \Huge` 


In yaml, you will need to use double backslashes for all LaTeX commands, For example,

``` yaml
title: "\\vskip 2cm \\bfseries Acute Beetroot Supplementation May Improve Blood Pressure \\\\ But Not Exercise Economy in Female Masters Swimmers"
format:
  apaquarto-pdf:
    journal: "\\bfseries \\Large Journal of Kinesiology and Wellness"
    volume: "\\vskip 1mm \\large A Publication of the Western Society for Kinesiology and Wellness \\newline Volume 12, Number 1, Pages 1--9, 2023\\newline ISSN# 2323-4505"
```
