### ISSUE TITLE
bad indentation error with apaquarto-pdf

### ISSUE THREAD

**Issue by schneiderpy** [wjschne/apaquarto#51]
I get a bad indentation error for apaquarto-pdf and documentmode: jou
```
format:
  #apaquarto-docx: default
  #apaquarto-html: default
  apaquarto-pdf: default
    # Can be jou (journal), man (manuscript), stu (student), or doc (document)
    documentmode: jou
    keep-tex: true
```
bad indentation of a mapping entry at line 37, column 5:
        documentmode: jou
        ^

**Comment by wjschne** [comment]
I think this error will go away if you remove `default` from the `apaquarto-pdf:` yaml:

```yaml
format:
  #apaquarto-docx: default
  #apaquarto-html: default
  apaquarto-pdf: 
    # Can be jou (journal), man (manuscript), stu (student), or doc (document)
    documentmode: jou
    keep-tex: true
```
