### ISSUE TITLE
document won't render to pdf if flextable included

### ISSUE THREAD

**Issue by torven-schalk** [wjschne/apaquarto#72]
when trying to render a document that includes a table created with `flextable::flextable()` it works for for apaquarto-docx but throws and error for apaquarto-pdf in both document and manuscript mode. If i try to render with quartos default pdf settings it also works. It only throws the error when using apaquarto-pdf.

this works

````
---
title: "test"
author:
  - name: Remus Lupin
    corresponding: true
    orcid: 0000-0000-0000-0000
    email: rlupin@hogwarts.mfm.ac.uk
    affiliations:
      - name: Hogwarts School of Whitchcraft and Wizardry
abstract: "This document is a template demonstrating the apaquarto format."
# Put as many keywords at you like, separated by commmas (e.g., [reliability, validity, generalizability])
keywords: [keyword1, keyword2, keyword3]
format: pdf
---

```{r}
library(flextable)
flextable(head(mtcars))
```
````

this also works

````
---
title: "test"
author:
  - name: Remus Lupin
    corresponding: true
    orcid: 0000-0000-0000-0000
    email: rlupin@hogwarts.mfm.ac.uk
    affiliations:
      - name: Hogwarts School of Whitchcraft and Wizardry
abstract: "This document is a template demonstrating the apaquarto format."
# Put as many keywords at you like, separated by commmas (e.g., [reliability, validity, generalizability])
keywords: [keyword1, keyword2, keyword3]
format:
  apaquarto-docx: default
---

```{r}
library(flextable)
flextable(head(mtcars))
```
````

but this doesn't work

````
---
title: "test"
author:
  - name: Remus Lupin
    corresponding: true
    orcid: 0000-0000-0000-0000
    email: rlupin@hogwarts.mfm.ac.uk
    affiliations:
      - name: Hogwarts School of Whitchcraft and Wizardry
abstract: "This document is a template demonstrating the apaquarto format."
# Put as many keywords at you like, separated by commmas (e.g., [reliability, validity, generalizability])
keywords: [keyword1, keyword2, keyword3]
format:
  apaquarto-pdf: default
---

```{r}
library(flextable)
flextable(head(mtcars))
```
````
