### ISSUE TITLE
pdf only renders in jou mode when table names include "_"

### ISSUE THREAD

**Issue by torven-schalk** [wjschne/apaquarto#73]
when I have a table in my document whose name/label includes an underscore the document will only render in jou mode but not in doc or man. it says 
ERROR: 
compilation failed- error
Missing \endcsname inserted.

this works in jou, man, and doc

````
---
title: "owl"
author:
  - name: Remus Lupin
    corresponding: true
    orcid: 0000-0000-0000-0000
    email: rlupin@hogwarts.mfm.ac.uk
    affiliations:
      - name: Hogwarts School of Whitchcraft and Wizardry
abstract: "This document is a template demonstrating the apaquarto format."
# Put as many keywords at you like, separated by commmas (e.g., [reliability, validity, generalizability])
keywords: [keyword1, keyword2, keyword3]
format:
  apaquarto-pdf:
    documentmode: man
---

Here is a table @tbl-Owlsarecool.

```{r}
#| label: tbl-Owlsarecool
#| tbl-cap: "Owlsarecool"
library(flextable)
flextable(head(mtcars))
```

````

this doesn't work in man and doc, but works in jou

````
---
title: "owl"
author:
  - name: Remus Lupin
    corresponding: true
    orcid: 0000-0000-0000-0000
    email: rlupin@hogwarts.mfm.ac.uk
    affiliations:
      - name: Hogwarts School of Whitchcraft and Wizardry
abstract: "This document is a template demonstrating the apaquarto format."
# Put as many keywords at you like, separated by commmas (e.g., [reliability, validity, generalizability])
keywords: [keyword1, keyword2, keyword3]
format:
  apaquarto-pdf:
    documentmode: man
---

Here is a table @tbl-Owls_are_cool.

```{r}
#| label: tbl-Owls_are_cool
#| tbl-cap: "Owls_are_cool is more legible"
library(flextable)
flextable(head(mtcars))
```

````
