### ISSUE TITLE
Content disappears in pdf documentmode: jou

### ISSUE THREAD

**Issue by mvuorre** [wjschne/apaquarto#74]
I am writing a PDF manuscript in jou mode and find that content keeps disappearing instead of wrapping to the next column / page. Here is an example where the table note is not visible--the table should be lifted to the next column e.g. This behavior is not limited to tables but text can disappear too, but in my experience only happens in documents that include at least one table.

````
---
title: "My Title"
shorttitle: "Short Title in Running Header"
author:
  - name: Jane Doe
    corresponding: true
    orcid: 0000-0000-0000-0001
    email: janedoe@generic.edu
    affiliations:
      - name: Generic University
        department: Department of Scholarly Studies
        address: 1234 Capital St.
        city: New York
        region: NY
        country: USA
        postal-code: 12084-1234
author-note:
  status-changes: 
    affiliation-change: ~
    deceased: ~
  disclosures:
    study-registration: ~
    data-sharing: ~
    related-report: ~
    conflict-of-interest: ~
    financial-support: ~
    gratitude: ~
    authorship-agreements: ~
abstract: "This document is a template."
keywords: [keyword1, keyword2, keyword3]
bibliography: bibliography.bib
number-lines: true
format:
  apaquarto-pdf:
    documentmode: jou
---

<!-- https://hipsum.co/ -->

I'm baby swag affogato bitters, vibecession small batch same pop-up next level flexitarian distillery try-hard selvage. Cornhole selvage heirloom, craft beer taiyaki tousled austin echo park. Roof party kickstarter next level fixie small batch helvetica master cleanse etsy. Austin shaman cronut kickstarter mukbang tousled neutra dreamcatcher activated charcoal gluten-free big mood godard vinyl affogato. Poutine umami whatever bespoke pop-up, irony pitchfork sartorial mukbang. Roof party solarpunk next level actually drinking vinegar sriracha vinyl sus tumblr yes plz. Ethical hexagon pabst jawn, mumblecore heirloom raw denim vibecession.

Next level heirloom plaid sartorial asymmetrical kitsch kale chips kombucha truffaut cronut jawn cardigan. Health goth heirloom banh mi irony. Kitsch blackbird spyplane shabby chic artisan stumptown palo santo kickstarter whatever kogi church-key gorpcore. Vinyl ethical gatekeep thundercats. Kinfolk vaporware jean shorts, banjo street art succulents affogato semiotics tumeric tote bag man braid paleo venmo.

```{r}
#| label: tbl-dat1
#| tbl-cap: This is a very long table caption. This is a very long table caption. This is a very long table caption.
#| apa-note: This is a very long table note. This is a very long table note. This is a very long table note.

set.seed(1)
dat <- data.frame(
  a = rnorm(10),
  b = rnorm(10)
)

library(knitr)
dat |>
  head() |>
  kable()
```

Palo santo waistcoat banh mi jean shorts, lomo fam copper mug williamsburg direct trade. Bicycle rights cornhole vegan try-hard, food truck synth YOLO stumptown paleo meditation coloring book deep v. Readymade deep v listicle pickled, direct trade polaroid beard celiac single-origin coffee humblebrag tousled prism paleo sus. Tilde vibecession taxidermy Brooklyn thundercats ugh blog beard farm-to-table jean shorts gochujang. Poutine beard next level kinfolk same.

Big mood kickstarter single-origin coffee skateboard sus keytar chicharrones lyft venmo. Sriracha dreamcatcher fam fingerstache kitsch. Lo-fi grailed kogi, post-ironic meggings af wolf JOMO sriracha hammock pork belly cray gastropub. Polaroid prism sustainable DIY. Williamsburg sartorial gentrify, kombucha mlkshk hashtag craft beer man braid. Cornhole single-origin coffee asymmetrical jawn, four dollar toast locavore fashion axe. Chambray unicorn skateboard pickled pok pok butcher, austin meggings quinoa lomo poke migas hashtag.

Ethical PBR&B heirloom shaman, helvetica kale chips Brooklyn fanny pack vegan disrupt typewriter fashion axe salvia subway tile. Roof party XOXO chartreuse polaroid hell of pork belly, DIY four loko yr PBR&B plaid adaptogen. Disrupt chia keffiyeh messenger bag craft beer. Chartreuse bruh deep v shoreditch tofu tousled, DIY man braid locavore green juice vibecession meh. Aesthetic yuccie authentic microdosing taiyaki neutral milk hotel humblebrag hell of disrupt post-ironic pabst. Kombucha cred mukbang selvage venmo stumptown. Stumptown put a bird on it tousled cred prism deep v, celiac iPhone bruh waistcoat butcher hammock meditation bespoke.
````

Results in the following document

<img width="759" alt="image" src="https://github.com/wjschne/apaquarto/assets/7349270/194ede3c-3cbc-43eb-8883-bb35274483d8">
