### ISSUE TITLE
Reference list is duplicated

### ISSUE THREAD

**Issue by tombeesley** [wjschne/apaquarto#82]
![image](https://github.com/user-attachments/assets/65df4cf4-4785-44fa-ba5e-48c436d24d3a)

This is the code I took from the example. My entire reference list is being duplicated. Is this an issue with the template?

**Comment by wjschne** [comment]
The example.qmd renders with only one set of references. Would you mind sending a minimal example file that produces duplicate references? That is, create an abbreviated document that produces this error. I am open to talking over Zoom if this problem persists.

**Comment by tombeesley** [comment]
[example.zip](https://github.com/user-attachments/files/16256314/example.zip)
I hope this contains all the files you need. Thanks so much.

**Comment by tombeesley** [comment]
Pretty sure it's generated by the citeproc.lua bit. I'm not sure when I put that in or what it was meant to be for. Issue resolved!

**Comment by wjschne** [comment]
Thanks! The problem is that your yaml adds a run to `citeproc`, but apaquarto already does this. So the references are run twice.  removing two lines fixes the problem. So the yaml should be:
``` yaml
format:
  apaquarto-pdf:
    link-citations: true
    numbered-lines: true
    fig-pos: 'H'
    documentmode: man
    keep-tex: true
    filters: 
      - at: pre-render
        path: "wordcount.lua"
```

Let me know if this fixes the problem.
