### ISSUE TITLE
ussing a different fon than Times Roman

### ISSUE THREAD

**Issue by JensBoelte** [wjschne/apaquarto#98]
Hello

I did not manage to change the font from Times Roman to Calibri or Arial by using ```mainfont```. I inserted the font specification at the top-level or under the ```apaquatro-key```.

```
format:
  apaquarto-html:
    fontsize: 11pt
    mainfont: "Calibri"
  apaquarto-docx:
    mainfont: "Calibri"
    fontsize: 11pt
```

Interestingly, the reference section 

![{6EE8EA1F-CFEB-4140-8FAF-66ECC2A2CD7A}](https://github.com/user-attachments/assets/e91604bc-ff77-40be-babd-770fcb14f103)

and the TOC on the left-hand side of the html document are set in Calibri and not Times Roman.

![{29D76120-6D12-48EB-9D3E-50443BB79D7E}](https://github.com/user-attachments/assets/0197ff34-18c1-45eb-997d-ac427a201b7a)

Any idea how I can get the main text including headings etc. in the same font as the references?

I am using quarto-version 1.5.57 from RStudio.

Thanks in advance.

Best wishes Jens
